# Generated by Django 4.2.11 on 2026-03-04 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(help_text='e.g., Programming, Soft Skill, Tool', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_level', models.CharField(help_text='e.g., Sophomore, Junior, Senior', max_length=100)),
                ('weekly_study_hours', models.IntegerField(default=10)),
                ('current_skills', models.ManyToManyField(blank=True, related_name='students', to='simulation.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('base_difficulty_level', models.IntegerField(default=1, help_text='Scale of 1-10')),
                ('estimated_months_to_entry', models.IntegerField(default=6, help_text='Average months to learn from scratch')),
                ('required_skills', models.ManyToManyField(related_name='careers', to='simulation.skill')),
            ],
        ),
    ]
